### ISSUE TITLE
Error when decode UL-DCCH-Message

### ISSUE THREAD

**Issue by vtandroid** [mitshell/libmich#11]
I decode this hex: '4b88000a6000042aaad506a556a88a48304480018001480cc0d5d62910c02808deca46043c49b84271cfbde899ebb65ca138e7def44cf5db2f509c73ef7a267aed97684e39f7bd133d76cbcb808fa208521c7af3d0d133d76cb6006407406c07635024f2188b00'
use: 
load_module('RRC3G') 
ASN1.ASN1Obj.CODEC = PER
PER.VARIANT = 'U'
pdu = GLOBAL.TYPE['UL-DCCH-Message']

Ouput print this exception:
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    pdu.decode(buf)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 632, in decode
    buf = self._decode(buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1145, in decode
    return self.decode_seq(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1818, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1143, in decode
    return self.decode_choice(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1670, in decode_choice
    buf = cho._decode(buf, offset=self._off)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1145, in decode
    return self.decode_seq(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1818, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1145, in decode
    return self.decode_seq(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1818, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1145, in decode
    return self.decode_seq(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1818, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1145, in decode
    return self.decode_seq(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1818, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1145, in decode
    return self.decode_seq(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1818, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "\libmich-master\libmich-master\libmich\asn1\ASN1.py", line 649, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1138, in decode
    return self.decode_bit_str(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1436, in decode_bit_str
    return self._decode_bit_str_noub(obj, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1491, in _decode_bit_str_noub
    buf = obj._cont._codec._get_P(obj._cont, buf)
  File "\libmich-master\libmich-master\libmich\asn1\PER.py", line 1164, in _get_P
    assert( p() == 0 )
AssertionError

**Comment by mitshell** [comment]
I am starting looking at this issue, and it may not be easy to solve.
In the meantime, can you tell me which modem did generate it (what phone / year / 3GPP release), and eventually how did you capture the RRC signalling ?

**Comment by vtandroid** [comment]
this modem is generated from 3gpp release 11 and capture from RNC log of Ericsson

**Comment by mitshell** [comment]
commit https://github.com/mitshell/libmich/commit/04392cc56ad3cd7cb95ebe092cfa6252e8ae6de8 should solve the issue.
In case you know which mobile generated this specific RRC frame, let me know.
