### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fourat** [mitshell/libmich#4]
Hi,

When trying to install i get the following error

    $ sudo python setup.py install
    [sudo] password for fourat: 
    running install
    [install] compiling ASN.1 modules... be patient
    processing Remote-Operations-Information-Objects.asn
    [proc] ASN.1 module Remote-Operations-Information-Objects: 11 assignments processed (9 pass)
    [proc] ASN.1 modules scanned: ['Remote-Operations-Information-Objects']
    processing MobileDomainDefinitions.asn
    [proc] ASN.1 module MobileDomainDefinitions: 11 assignments processed (6 pass)
    [proc] ASN.1 modules scanned: ['MobileDomainDefinitions']
    processing MAP-ApplicationContexts.asn
    [proc] ASN.1 module MAP-ApplicationContexts: 45 assignments processed (7 pass)
    [proc] ASN.1 modules scanned: ['MAP-ApplicationContexts']
    processing MAP-ExtensionDataTypes.asn
    [proc] ASN.1 module MAP-ExtensionDataTypes: 9 assignments processed (7 pass)
    [proc] ASN.1 modules scanned: ['MAP-ExtensionDataTypes']
    processing MAP-BS-Code.asn
    [proc] ASN.1 module MAP-BS-Code: 54 assignments processed (7 pass)
    [proc] ASN.1 modules scanned: ['MAP-BS-Code']
    processing MAP-SS-Code.asn
    [proc] ASN.1 module MAP-SS-Code: 73 assignments processed (8 pass)
    [proc] ASN.1 modules scanned: ['MAP-SS-Code']
    processing MAP-TS-Code.asn
    [proc] ASN.1 module MAP-TS-Code: 34 assignments processed (7 pass)
    [proc] ASN.1 modules scanned: ['MAP-TS-Code']
    processing MAP-CommonDataTypes.asn
    [proc] ASN.1 module MAP-CommonDataTypes: 161 assignments processed (10 pass)
    [proc] ASN.1 modules scanned: ['MAP-CommonDataTypes']
    processing MAP-SS-DataTypes.asn
    [proc] ASN.1 module MAP-SS-DataTypes: 45 assignments processed (9 pass)
    [proc] ASN.1 modules scanned: ['MAP-SS-DataTypes']
    processing MAP-ER-DataTypes.asn
    [proc] ASN.1 module MAP-ER-DataTypes: 60 assignments processed (8 pass)
    [proc] ASN.1 modules scanned: ['MAP-ER-DataTypes']
    processing MAP-OM-DataTypes.asn
    [proc] ASN.1 module MAP-OM-DataTypes: 56 assignments processed (10 pass)
    [proc] ASN.1 modules scanned: ['MAP-OM-DataTypes']
    processing MAP-MS-DataTypes.asn
    Traceback (most recent call last):
      File "setup.py", line 38, in <module>
        cmdclass={"install": my_install},
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setup.py", line 14, in run
        preinstall()
      File "/home/fourat/workspace/libmich/preinstall.py", line 7, in main
        generate_modules(MODULES)
      File "/home/fourat/workspace/libmich/libmich/asn1/processor.py", line 152, in generate_modules
        M.extend( compile(text) )
      File "/home/fourat/workspace/libmich/libmich/asn1/processor.py", line 66, in compile
        M = process_modules(texts)
      File "/home/fourat/workspace/libmich/libmich/asn1/processor.py", line 276, in process_modules
        obj_nums, module['obj'] = process_module_content( module )
      File "/home/fourat/workspace/libmich/libmich/asn1/processor.py", line 504, in process_module_content
        process_module_content_pass(obj_num, obj_list)
      File "/home/fourat/workspace/libmich/libmich/asn1/processor.py", line 513, in process_module_content_pass
        process_assignment(obj)
      File "/home/fourat/workspace/libmich/libmich/asn1/processor.py", line 583, in process_assignment
        text_def  = Obj.parse_definition(Obj._text_def)
      File "/home/fourat/workspace/libmich/libmich/asn1/ASN1.py", line 817, in parse_definition
        text = self._parse_content_dispatch(text)
      File "/home/fourat/workspace/libmich/libmich/asn1/ASN1.py", line 855, in _parse_content_dispatch
        return self._parse_content_constructed(text)
      File "/home/fourat/workspace/libmich/libmich/asn1/ASN1.py", line 877, in _parse_content_constructed
        text = parsers.parse_content_constructed(self, text)
      File "/home/fourat/workspace/libmich/libmich/asn1/parsers.py", line 418, in parse_content_constructed
        _process_components(Obj, text_cont)
      File "/home/fourat/workspace/libmich/libmich/asn1/parsers.py", line 490, in _process_components
        comp = parse_definition(Cont[name], comp)
      File "/home/fourat/workspace/libmich/libmich/asn1/parsers.py", line 103, in parse_definition
        return Obj.parse_definition(text)
      File "/home/fourat/workspace/libmich/libmich/asn1/ASN1.py", line 816, in parse_definition
        text = self._parse_type(text)
      File "/home/fourat/workspace/libmich/libmich/asn1/ASN1.py", line 829, in _parse_type
        return parsers.parse_type(self, text)
      File "/home/fourat/workspace/libmich/libmich/asn1/parsers.py", line 234, in parse_type
        raise(ASN1_PROC_TEXT('%s: invalid ASN.1 type %s' % (Obj.get_fullname(), text)))
    libmich.asn1.utils.ASN1_PROC_TEXT: Ext-CwFeature.basicService: invalid ASN.1 type �Ext-BasicServiceCode

**Comment by mitshell** [comment]
I just commited a change that should solve this (some \t encoding where corrupted...).
Let me know if this works now. Thanks

**Comment by fourat** [comment]
Confirmed
