### ISSUE TITLE
Error decoding S1AP-PDU

### ISSUE THREAD

**Issue by novadacalo** [mitshell/libmich#5]
Hi,

When trying to decode the next message:
00050080b700000400000005c010bbce26000800048061fed80042000a18091eb7806001ab5e40001000809000001100808a0a0008310f80a689f7d6915600897b27280b4a9503b72c48a7d976920cc69de8982737bd5ac3d8d39684e71202fd1305deb129a2e837c09d0294642e63a1282c91a67deb22a0da337f6725f3a38b380a979e955e3a9262b33df74850f037133db1f8eb7e07ddbe3357c675cf65cb4c20a56a1b1dee8ca3fb3b9cee108fccfcb1a6ee65cb4e3cc6fe07f3

I get the next error:

```
Traceback (most recent call last):
  File "<module4>", line 31, in <module>
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 633, in decode
    buf = self._decode(buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 650, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1131, in decode
    return self.decode_choice(obj, buf)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1634, in decode_choice
    buf = cho._decode(buf, offset=self._off)
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 650, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1133, in decode
    return self.decode_seq(obj, buf)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1776, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 650, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1137, in decode
    return self.decode_open_type(obj, buf)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1946, in decode_open_type
    buf = self._unwrap_open_type(obj, buf, obj._cont)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1699, in _unwrap_open_type
    buf = wrapped._decode(buf, offset=0)
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 650, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1133, in decode
    return self.decode_seq(obj, buf)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1776, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 650, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1135, in decode
    return self.decode_seq_of(obj, buf)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1913, in decode_seq_of
    return self._decode_seq_of_obj(obj, buf, size)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1932, in _decode_seq_of_obj
    buf = cont._decode(buf, offset=self._off)
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 650, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1133, in decode
    return self.decode_seq(obj, buf)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1776, in decode_seq
    buf = comp._decode(buf, offset=self._off)
  File "C:\Python27\lib\site-packages\libmich\asn1\ASN1.py", line 650, in _decode
    buf = self._codec.decode(self, buf, **kwargs)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1137, in decode
    return self.decode_open_type(obj, buf)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1946, in decode_open_type
    buf = self._unwrap_open_type(obj, buf, obj._cont)
  File "C:\Python27\lib\site-packages\libmich\asn1\PER.py", line 1707, in _unwrap_open_type
    assert( wrapped._msg.bit_len() == size*8 )
AssertionError
```

This is the code I used for it:
```
from libmich.asn1.processor import load_module
from libmich.asn1.processor import *

load_module('S1AP')

ASN1.ASN1Obj.CODEC = PER
PER.VARIANT = 'A'

eRAB_sr = GLOBAL.TYPE['S1AP-PDU']

decoded_message="00050080b700000400000005c010bbce26000800048061fed80042000a18091eb7806001ab5e40001000809000001100808a0a0008310f80a689f7d6915600897b27280b4a9503b72c48a7d976920cc69de8982737bd5ac3d8d39684e71202fd1305deb129a2e837c09d0294642e63a1282c91a67deb22a0da337f6725f3a38b380a979e955e3a9262b33df74850f037133db1f8eb7e07ddbe3357c675cf65cb4c20a56a1b1dee8ca3fb3b9cee108fccfcb1a6ee65cb4e3cc6fe07f3".decode('hex')
eRAB_sr.decode(decoded_message)
content_obj = eRAB_sr()
```

Any ideas?
Thanks

**Comment by mitshell** [comment]
Hello,
last commit (509033d) should solve the problem. Please verify on your side and let me know if it's OK : I'll close the issue

**Comment by novadacalo** [comment]
It does! You can close it.
Thanks a lot for your quick reply.
